### ISSUE TITLE
Support for monochrome framebuffer

### ISSUE THREAD

**Issue by ederguidsa** [littlevgl/lv_drivers#31]
Currently, fbdev driver does not support monochrome framebuffers. 
The attached patch adresses this issue. I've tested on linux with ssd1307 frame buffer driver (https://github.com/torvalds/linux/blob/master/drivers/video/fbdev/ssd1307fb.c) and it worked perfectly.

[fbdev_patch.txt](https://github.com/littlevgl/lv_drivers/files/2510837/fbdev_patch.txt)

**Comment by kisvegabor** [comment]
Hi,

Thank you!

Can add your update as a Pull request?
