### ISSUE TITLE
Apply calibration to evdev touchscreen and swap/invert axes

### ISSUE THREAD

**Issue by stheil** [littlevgl/lv_drivers#37]
Hi,

I have a touchscreen that - similar to issue #35 - has a scaling that doesn't equal the display resolution. Additionally the x and y axes are swapped and the reported coordinates have quite a big offset from 0 and 4096, resp. I do have an xorg.conf that came with the screen and contains the calibration values.

I added options to swap x and y axes, invert one or both axes (on my touchscreen the x axis is inverted) and apply min/max values for the x and y axes to calibrate the screen. I'd be happy to create a pull request if you're interested.

**Comment by kisvegabor** [comment]
Hi,

Sound great! A PR would be welcome!
