### ISSUE TITLE
Suggestions for setting input devices.

### ISSUE THREAD

**Issue by chaos4284** [littlevgl/lv_drivers#43]
In raspberry pie, the device name of the touch screen and the mouse changes each time depending on whether the mouse is used or not. When the mouse is connected / dev / input / event0 (mouse) and / dev / input / event1 (touch screen), If the mouse is not connected / dev / input / event1 (touch screen).
Therefore,  I want to modify a function that can set the touch screen device in such a way that the driver parameter is passed to the function instead of the method defined in the existing lv_drv_conf.h.

~before
evdev_init()

~after
evdev_init(char* device_name)

**Comment by kisvegabor** [comment]
Hi,

It sounds like a reasonable improvement. However, I would rather prefer a new function because now all the `init` and `read` function have the same prototype. 

For example: `evdev_set_file(dev_name)`

**Comment by kisvegabor** [comment]
See #44
