### ISSUE TITLE
Added touch screen device file setting function of evdev.

### ISSUE THREAD

**Issue by chaos4284** [littlevgl/lv_drivers#44]
Hi,
I want to add the function as follows:
### evdev.c
    bool evdev_set_file(char* dev_name)
    { 
         if(evdev_fd != -1) {
            close(evdev_fd);
         }
         evdev_fd = open(dev_name, O_RDWR | O_NOCTTY | O_NDELAY);

         if(evdev_fd == -1) {
            perror("unable open evdev interface:");
            return false;
         }

         fcntl(evdev_fd, F_SETFL, O_ASYNC | O_NONBLOCK);

         evdev_root_x = 0;
         evdev_root_y = 0;
         evdev_button = LV_INDEV_STATE_REL;

         return true;
    }

Can I commit & push? Or do you have additional code rules to follow?

**Comment by kisvegabor** [comment]
Hi,
It seems perfect :)
A PR would be welcome!
