### ISSUE TITLE
Extra SDL.h include breaks Visual Studio pc simulator build

### ISSUE THREAD

**Issue by MCF** [littlevgl/lv_drivers#46]
This include causes the visual studio pc simulator build to break:

https://github.com/littlevgl/lv_drivers/blob/78c4601f7132da08666bc180c08cafc5773234c5/indev/mouse.h#L26

It looks like that line can be deleted for both GCC and visual studio as that include will be pulled in by the `MONITOR_SDL_INCLUDE_PATH` macro instead (default handled a couple of lines lower).

**Comment by kisvegabor** [comment]
Fixed, Thank you!
