### ISSUE TITLE
Defaults for MONITOR_HOR_RES & MONITOR_VER_RES ?

### ISSUE THREAD

**Issue by puzrin** [littlevgl/lv_drivers#70]
https://github.com/littlevgl/lv_platformio/blob/master/platformio.ini#L26-L27

Now need to define MONITOR_HOR_RES & MONITOR_VER_RES in every platform.ini. Not a problem, but in 99% looks like useless garbage.

May be worth add such fallback defines near MONITOR_ZOOM ?

https://github.com/littlevgl/lv_drivers/blob/master/display/monitor.c#L29-L31

**Comment by kisvegabor** [comment]
I see no problem with adding them similarly to `MONITOR_ZOOM`.
