### ISSUE TITLE
XPT2046 driver gives jumping results

### ISSUE THREAD

**Issue by JojoS62** [littlevgl/lv_drivers#82]
The driver is not up to date, the result code for the read should always return false.  When implemented as in this sample, the touch does not respond precisely. The returned x/y coordinates have a variation of about 30 pixels on the same position.
https://github.com/littlevgl/lv_drivers/blob/9fb21b087b52b46eca015d80d27eefcd71739786/indev/XPT2046.c#L109
The porting template in lvgl is correct:
https://github.com/littlevgl/lvgl/blob/master/porting/lv_port_indev_template.c

**Comment by embeddedt** [comment]
True; can you send a PR please?

**Comment by JojoS62** [comment]
yes, I will prepare it.

**Comment by embeddedt** [comment]
#83 was merged, closing.
