### ISSUE TITLE
Touchscreen Problem after upgrading lv_drivers folder

### ISSUE THREAD

**Issue by AnneBruner** [littlevgl/lv_drivers#92]
After updating the lv_drivers folder for our application, the X/Y coordinates being reported to our application are not correct. Looks like the problem is in evdev.c and is related to the check in commited on Nov 24, 2019.

In our case, the data->point.x/y calculated in the #if EVDEV_SCALE section is being overwritten by the #else portion of the #if EV_CALIBRATE section (lines 189-199). 

I am not sure what case the Nov 2019 checkin was addressing but looks like the code will now always override the x/y values calculated using the scaling code. So I'm not sure if that check in should just be reverted or if it needs modified in some manner.

**Comment by embeddedt** [comment]
> I am not sure what case the Nov 2019 checkin was addressing

See #86.
